"""README 生成器。

交付者 Agent 统一调用它生成中英文（及其他语言）README，写入 readmes 目录。
文件名约定：
- 英文: README.md
- 中文: README_zh.md
- 其他语言: README_<语言名>.md
"""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _task_table(tasks: list[dict[str, Any]]) -> str:
    lines = ["| 任务 | 执行者 | 状态 | 优先级 | 产物 |", "| --- | --- | --- | --- | --- |"]
    for t in tasks:
        agents = {a["id"]: a["name"] for a in t.get("_agents", [])}
        assignee = agents.get(t.get("assignee_id", 0), "—")
        lines.append(
            f"| {t.get('name','')} | {assignee} | {t.get('status','')} | "
            f"{t.get('priority','')} | {t.get('artifact_count', 0)} 项 |"
        )
    return "\n".join(lines)


def build_en_readme(meta: dict[str, Any]) -> str:
    """生成英文 README 内容。"""
    return (
        f"# {meta['project_name']}\n\n"
        f"> Generated by HiveLab multi-agent collaboration.\n\n"
        f"## Requirement\n\n{meta['requirement']}\n\n"
        f"## Project Status\n\n- Status: **{meta['project_status']}**\n"
        f"- Executed by Planner, {meta['executer_count']} Executive Agent(s) and a Deliverer Agent.\n\n"
        f"## Tasks\n\n{_task_table(meta['tasks'])}\n\n"
        f"## Artifacts\n\n"
    ) + _artifact_lines(meta) + (
        f"\n## Smoke Test\n\n- Result: **{meta['smoke']['status']}**\n"
        f"```text\n{meta['smoke']['summary']}\n```\n"
        f"\n---\n*Powered by [HiveLab](https://hivelab.local).*\n"
    )


def build_zh_readme(meta: dict[str, Any]) -> str:
    """生成中文 README 内容。"""
    return (
        f"# {meta['project_name']}\n\n"
        f"> 由 HiveLab 多 Agent 协作平台生成。\n\n"
        f"## 需求\n\n{meta['requirement']}\n\n"
        f"## 项目状态\n\n- 状态：**{meta['project_status']}**\n"
        f"- 由规划者 Agent、{meta['executer_count']} 个执行 Agent 与交付者 Agent 协作完成。\n\n"
        f"## 任务\n\n{_task_table(meta['tasks'])}\n\n"
        f"## 产物\n\n"
    ) + _artifact_lines(meta) + (
        f"\n## 冒烟测试\n\n- 结果：**{meta['smoke']['status']}**\n"
        f"```text\n{meta['smoke']['summary']}\n```\n"
    )


def _artifact_lines(meta: dict[str, Any]) -> str:
    arts = meta.get("artifacts", [])
    if not arts:
        return "- （无）\n"
    return "\n".join(f"- `{a['path']}` — {a['description']}" for a in arts) + "\n"


LANG_FILENAME = {
    "en": "README.md",
    "zh": "README_zh.md",
}


def write_readmes(project_dir: Path, meta: dict[str, Any], extra_langs: list[str] | None = None) -> list[Path]:
    """把 README 写入 project_dir/readmes，返回生成的文件列表。"""
    readmes_dir = project_dir / "readmes"
    readmes_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    mapping = {
        "en": ("README.md", build_en_readme),
        "zh": ("README_zh.md", build_zh_readme),
    }
    for lang, extra in (extra_langs or []):
        if lang not in mapping:
            # 其他语言：以该语言名作为英文 README 的本地化名（可扩展）
            mapping[lang] = (f"README_{lang}.md", lambda m, e=meta: build_en_readme(m) + "")
    for lang, (fname, builder) in mapping.items():
        data = {**meta}
        data["lang"] = lang
        path = readmes_dir / fname
        path.write_text(builder(data), encoding="utf-8")
        written.append(path)
    return written